# Fichier de configuration Jupyter Book

title: "TP SQL — Jupyter Book"
author: "Gasmi Rémy"
logo: logo.png

# Dossier d'output
output_dir: _build
only_build_toc_files: false


# Activer les extensions Markdown utiles
parse:
  myst_enable_extensions:
    - colon_fence           # ::: blocks
    - deflist               # listes de définitions
    - dollarmath            # $math$
    - amsmath               # equations en bloc
    - html_admonition       # notes type "note", "warning"
    - html_image            # images HTML
    - linkify               # détection automatique de liens
    - substitution          # variables {sub}

# Gestion de l’exécution
execute:
  execute_notebooks: "off"  # tu peux mettre "force" si tu veux exécuter tout à chaque build
  timeout: 60

# Références bibliographiques
bibtex_bibfiles:
  - references.bib

# Ajoute une barre latérale avec navigation
html:
  navbar_number_sections: true
  use_repository_button: false
  use_issues_button: false
  use_edit_page_button: false
  extra_navbar: ""
  extra_footer: "© 2025 — TP SQL"

# Ignorer certains fichiers
exclude_patterns:
  - "**/.ipynb_checkpoints"
  - "**/.*"
  - "**/__pycache__"
  - "**/*.pyc"
  - "**/*.tmp"

# Ajoute des fichiers supplémentaires
extra_files:
  - "../images/"
